homework_07/library/urls.py
from django.urls import path
from . import views

app_name = "library"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("genres/", views.genres_with_books, name="genres-with-books")
]

homework_07/library/views.py
from django.http import HttpRequest
from django.shortcuts import render
from .models import Genre, Book


def index_view(request):
    books = (
        Book
        .objects.select_related("genre")
        .all()
    )
    context = {
        "books": books,
    }
    return render(
        request,
        "library/books-list.html",
        context
    )


def genres_with_books(request: HttpRequest):
    context = {
        "genres": (
            Genre
            .objects
            .prefetch_related("books")
            .all()
        )
    }
    return render(
        request,
        "library/genres-with-books.html",
        context,
    )

homework_07/library/templates/library/books-list.html
{% extends 'base.html' %}

{% block title %}
  Books
{% endblock %}

{% block body %}
  <h1>Books:</h1>
  {% if books %}
    <ul>
      {% for book in books %}
        <li>
          <strong>{{ book.name }}</strong> <em>({{ book.genre.name }})</em>.
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No books yet!</h2>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_07/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Library Homepage
{% endblock %}

{% block body %}
  <h1>Welcome to our librery!</h1>
  <ul>
    <li><a href="{% url 'library:index' %}"
    >Books</a></li>
    <li><a href="{% url 'library:genres-with-books' %}"
    >Genres</a></li>
  </ul>
{% endblock %}