Library/books/urls.py
from django.urls import path
from . import views


app_name = "books"

urlpatterns = [
    path(
        "",
         views.BookListView.as_view(),
         name="list"
    ),
    path(
        "detail/<int:pk>",
        views.BookDetailView.as_view(),
        name="detail"
    ),
    path(
        "create",
        views.BookCreateView.as_view(),
        name="create"
    ),
    path(
        "update/<int:pk>/",
        views.BookUpdateView.as_view(),
        name="update"
    ),
    path(
        "delete/<int:pk>/",
        views.BookDeleteView.as_view(),
        name="delete"
    ),
    path(
        "create_copy/",
        views.CopyBookCreateView.as_view(),
        name="create_copy"
    ),
    path(
        "copy_list/",
        views.CopyBookListView.as_view(),
        name="copy_list"
    ),
    path(
        "copy_last/",
        views.last_copy_book,
        name="copy_last"
    ),
    path(
        "copy_detail/<int:pk>",
        views.CopyDetailView.as_view(),
        name="copy_detail"
    ),
    path(
        "copy_delete/<int:pk>/",
        views.CopyDeleteView.as_view(),
        name="copy_delete"
    ),
    path(
        "create_genre",
        views.GenreCreateView.as_view(),
        name="create_genre"
    ),
    path(
        "genre_list",
        views.GenreListView.as_view(),
        name="genre_list"
    ),
    path(
        "genre_delete/<int:pk>/",
        views.GenreDeleteView.as_view(),
        name="genre_delete"
    ),
    path(
        "author_list",
        views.AuthorListView.as_view(),
        name="author_list"
    ),
    path(
        "create_author",
        views.AuthorCreateView.as_view(),
        name="create_author"
    ),
    path(
        "author_update/<int:pk>",
        views.AuthorUpdateView.as_view(),
        name="author_update"
    ),
    path(
        "author_delete/<int:pk>/",
        views.AuthorDeleteView.as_view(),
        name="author_delete"
    ),
    path(
        "reader_list",
        views.ReaderListView.as_view(),
        name="reader_list"
    ),
    path(
        "reader_create",
        views.ReaderCreateView.as_view(),
        name="reader_create"
    ),
    path(
        "reader_detail/<int:pk>",
        views.ReaderDetailView.as_view(),
        name="reader_detail"
    ),
    path(
        "reader_update/<int:pk>",
        views.ReaderUpdateView.as_view(),
        name="reader_update"
    ),
    path(
        "reader_delete/<int:pk>",
        views.ReaderDeleteView.as_view(),
        name="reader_delete"
    ),
    path(
        "accounting_books_list",
        views.BookIssuanceAccountingListView.as_view(),
        name="accounting_books_list"
    ),
    path(
        "accounting_books_create",
        views.BookIssuanceAccountingCreateView.as_view(),
        name="accounting_books_create"
    ),
    path(
        "accounting_book_detail/<int:pk>",
        views.BookIssuanceAccountingDetailView.as_view(),
        name="accounting_book_detail"
    ),
    path(
        "accounting_book_update/<int:pk>",
        views.BookIssuanceAccountingUpdateView.as_view(),
        name="accounting_book_update"
    ),
    path(
        "accounting_book_update/<int:pk>",
        views.BookIssuanceAccountingUpdateView.as_view(),
        name="accounting_book_update"
    ),
    # path(
    #     "author_by_book",
    #     views.AuthorBookListView.as_view(),
    #     name="author_by_book"
    # ),
    path(
        "debt_list/",
        views.debt_list,
        name="debt_list"
    ),
]


Library/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("books/", include("books.urls")),
    path("users/", include("users.urls", namespace='users')),
]

Library/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import users.views as myauth

app_name = 'myauth'

urlpatterns = [
    path("register/", myauth.MyUserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirm', myauth.logout_confirm, name='logout-confirm'),
]

Library/templates/back-to-index-common.html
<div>
  <a href="{% url 'index' %}">На главную страницу</a>
</div>

Library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
  {% if user.is_authenticated %}
    <a href="{% url 'users:logout-confirm' %}">Log out </a>
  {% else %}
    <a href="{% url 'users:login' %}">Log in</a>
    <a href="{% url 'users:register' %}">Register</a>
  {% endif %}
{% block body %}
	Base body
{% endblock %}
</body>
</html>

Library/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Black Library Homepage
{% endblock %}

{% block body %}
  <h1>Welcome to Black library</h1>
  <ul>
    <li><a href="{% url 'books:list' %}"
    >Список книг</a></li>
  </ul>
  <ul>
    <li><a href="{% url 'books:reader_list' %}"
    >Библиотечные карточки читателей</a></li>
  </ul>
  <ul>
    <li><a href="{% url 'books:author_list' %}"
    >Авторы</a></li>
  </ul>
  <ul>
    <li><a href="{% url 'books:genre_list' %}"
    >Жанры</a></li>
  </ul>
  <ul>
    <li><a href="{% url 'books:accounting_books_list' %}"
    >Учет выданных книг</a></li>
  </ul>
{% endblock %}