Library/books/urls.py
from django.urls import path
from . import views


app_name = "books"

urlpatterns = [
    path(
        "",
         views.BookListView.as_view(),
         name="list"
    ),
    path(
        "detail/<int:pk>",
        views.BookDetailView.as_view(),
        name="detail"
    ),
    path(
        "create",
        views.BookCreateView.as_view(),
        name="create"
    ),
    path(
        "update/<int:pk>/",
        views.BookUpdateView.as_view(),
        name="update"
    ),
    path(
        "delete/<int:pk>/",
        views.BookDeleteView.as_view(),
        name="delete"
    ),
    path(
        "create_copy/",
        views.CopyBookCreateView.as_view(),
        name="create_copy"
    ),
    path(
        "copy_list/",
        views.CopyBookListView.as_view(),
        name="copy_list"
    ),
    path(
        "copy_last/",
        views.last_copy_book,
        name="copy_last"
    ),
    path(
        "copy_detail/<int:pk>",
        views.CopyDetailView.as_view(),
        name="copy_detail"
    ),
    path(
        "copy_delete/<int:pk>/",
        views.CopyDeleteView.as_view(),
        name="copy_delete"
    ),
    path(
        "create_genre",
        views.GenreCreateView.as_view(),
        name="create_genre"
    ),
    path(
        "genre_list",
        views.GenreListView.as_view(),
        name="genre_list"
    ),
    path(
        "genre_delete/<int:pk>/",
        views.GenreDeleteView.as_view(),
        name="genre_delete"
    ),
    path(
        "author_list",
        views.AuthorListView.as_view(),
        name="author_list"
    ),
    path(
        "create_author",
        views.AuthorCreateView.as_view(),
        name="create_author"
    ),
    path(
        "author_update/<int:pk>",
        views.AuthorUpdateView.as_view(),
        name="author_update"
    ),
    path(
        "author_delete/<int:pk>/",
        views.AuthorDeleteView.as_view(),
        name="author_delete"
    ),
    path(
        "reader_list",
        views.ReaderListView.as_view(),
        name="reader_list"
    ),
    path(
        "reader_create",
        views.ReaderCreateView.as_view(),
        name="reader_create"
    ),
    path(
        "reader_detail/<int:pk>",
        views.ReaderDetailView.as_view(),
        name="reader_detail"
    ),
    path(
        "reader_update/<int:pk>",
        views.ReaderUpdateView.as_view(),
        name="reader_update"
    ),
    path(
        "reader_delete/<int:pk>",
        views.ReaderDeleteView.as_view(),
        name="reader_delete"
    ),
    path(
        "accounting_books_list",
        views.BookIssuanceAccountingListView.as_view(),
        name="accounting_books_list"
    ),
    path(
        "accounting_books_create",
        views.BookIssuanceAccountingCreateView.as_view(),
        name="accounting_books_create"
    ),
    path(
        "accounting_book_detail/<int:pk>",
        views.BookIssuanceAccountingDetailView.as_view(),
        name="accounting_book_detail"
    ),
    path(
        "accounting_book_update/<int:pk>",
        views.BookIssuanceAccountingUpdateView.as_view(),
        name="accounting_book_update"
    ),
    path(
        "accounting_book_update/<int:pk>",
        views.BookIssuanceAccountingUpdateView.as_view(),
        name="accounting_book_update"
    ),
    # path(
    #     "author_by_book",
    #     views.AuthorBookListView.as_view(),
    #     name="author_by_book"
    # ),
    path(
        "debt_list/",
        views.debt_list,
        name="debt_list"
    ),
]


Library/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("books/", include("books.urls")),
    path("users/", include("users.urls", namespace='users')),
]

Library/books/models.py
from django.db import models
from django.db.models import DateTimeField
from django.db.models import PositiveIntegerField


class Genre(models.Model):
    class Meta:
        verbose_name_plural = "Жанры"

    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    class Meta:
        verbose_name_plural = "Авторы"

    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    class Meta:
        verbose_name_plural = "Книги"

    name = models.CharField(max_length=64, unique=True)
    author = models.ForeignKey(
        Author,
        on_delete=models.PROTECT,
        related_name="books",
    )
    genre = models.ForeignKey(
        Genre,
        on_delete=models.PROTECT,
        related_name="books",
    )
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class CopyBook(models.Model):
    class Meta:
        verbose_name_plural = "Экземпляры книг"

    registration_date = DateTimeField(
        auto_now_add=True,
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.book.name


class Reader(models.Model):
    class Meta:
        verbose_name_plural = "Библиотечная карточка читателя"

    name = models.CharField(max_length=64, unique=True)
    address = models.CharField(max_length=999)
    email = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class BookIssuanceAccounting(models.Model):
    class Meta:
        verbose_name_plural = "Учет выдачи книг"

    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )
    copy_book = models.OneToOneField(
        CopyBook,
        on_delete=models.CASCADE,
    )
    reader = models.ForeignKey(
        Reader,
        on_delete=models.CASCADE,
        related_name="debt_books",
    )
    date_of_issue = models.DateField(auto_now_add=True)
    return_date = models.DateField(auto_now=False)
    return_book = models.BooleanField(null=True, blank=True)


Library/books/forms.py
from django import forms

from .models import Book, Author, Genre, Reader, BookIssuanceAccounting, CopyBook


class BookForm(forms.ModelForm):
    name = forms.CharField(label="Название книги")
    author = forms.ModelChoiceField(queryset=Author.objects.all(), label="Имя автора книги")
    genre = forms.ModelChoiceField(queryset=Genre.objects.all(), label="Жанр книги")
    description = forms.CharField(widget=forms.Textarea, label="Описание")

    class Meta:
        model = Book
        fields = "__all__"


class ReaderForm(forms.ModelForm):
    name = forms.CharField(label="Имя читателя")
    address = forms.CharField(label="Адрес читателя")
    email = forms.CharField(label="Электронная почта читателя")

    class Meta:
        model = Reader
        fields = "__all__"


class BookIssuanceAccountingForm(forms.ModelForm):
    book = forms.ModelChoiceField(queryset=Book.objects.all(), label="Наименование книги")
    copy_book = forms.ModelChoiceField(queryset=CopyBook.objects.all(), label="Инвентарный номер книги")
    reader = forms.ModelChoiceField(queryset=Reader.objects.all(), label="Кому выдается книга")
    return_date = forms.DateField(label="Дата возврата книги")
    # return_book = forms.BooleanField(label="Возвращена")

    class Meta:
        model = BookIssuanceAccounting
        fields = "__all__"

Library/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .forms import BookForm, ReaderForm, BookIssuanceAccountingForm
from .models import Book, CopyBook, Genre, Author, Reader, BookIssuanceAccounting


class BookListView(ListView):
    queryset = Book.objects.order_by("name")
    template_name = "books/book-list.html"
    context_object_name = "books"


class BookDetailView(DetailView):
    model = Book
    form_class = BookForm
    template_name = "books/book-detail.html"
    context_object_name = "book"


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = "books/book-form.html"
    success_url = reverse_lazy("books:list")


class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = "books/book-form.html"
    success_url = reverse_lazy("books:list")


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy("books:list")


class CopyBookListView(LoginRequiredMixin, ListView):
    model = CopyBook
    fields = "__all__"
    context_object_name = "copies_books"
    template_name = "books/copy-list.html"


class CopyBookCreateView(LoginRequiredMixin, CreateView):
    model = CopyBook
    fields = "__all__"
    template_name = "books/copy-book.html"
    success_url = reverse_lazy('books:copy_last')


def last_copy_book(request: HttpRequest):
    context = {"copy": (CopyBook.objects.all().last())}
    return render(request,"books/copy-last.html", context)


class CopyDetailView(LoginRequiredMixin, DetailView):
    model = CopyBook
    template_name = "books/copy-detail.html"

class CopyDeleteView(LoginRequiredMixin, DeleteView):
    model = CopyBook
    success_url = reverse_lazy("books:copy_list")


class GenreListView(ListView):
    model = Genre
    template_name = "books/genre-list.html"
    context_object_name = "genres"

class GenreCreateView(LoginRequiredMixin, CreateView):
    model = Genre
    fields = "__all__"
    template_name = "books/genre-form.html"
    success_url = reverse_lazy("books:genre_list")


class GenreDeleteView(LoginRequiredMixin, DeleteView):
    model = Genre
    success_url = reverse_lazy("books:genre_list")


class AuthorListView(ListView):
    queryset = Author.objects.order_by("name")
    template_name = "books/author-list.html"
    context_object_name = "authors"


class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    fields = "__all__"
    template_name = "books/author-form.html"
    success_url = reverse_lazy("books:author_list")


class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    model = Author
    fields = "__all__"
    template_name = "books/author-form.html"
    success_url = reverse_lazy("books:author_list")


class AuthorDeleteView(LoginRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy("books:author_list")


class ReaderListView(LoginRequiredMixin, ListView):
    queryset = Reader.objects.order_by("name")
    template_name = "books/reader-list.html"
    context_object_name = "readers"



class ReaderCreateView(LoginRequiredMixin, CreateView):
    model = Reader
    form_class = ReaderForm
    template_name = "books/reader-form.html"
    success_url = reverse_lazy("books:reader_list")


class ReaderDetailView(LoginRequiredMixin, DetailView):
    model = Reader
    form_class = ReaderForm
    template_name = "books/reader-detail.html"
    context_object_name = "reader"


class ReaderUpdateView(LoginRequiredMixin, UpdateView):
    model = Reader
    form_class = ReaderForm
    template_name = "books/reader-form.html"
    success_url = reverse_lazy("books:reader_list")


class ReaderDeleteView(LoginRequiredMixin, DeleteView):
    model = Reader
    success_url = reverse_lazy("books:reader_list")


class BookIssuanceAccountingListView(LoginRequiredMixin, ListView):
    model = BookIssuanceAccounting
    template_name = "books/accounting-books-list.html"
    context_object_name = "books"



class BookIssuanceAccountingDetailView(LoginRequiredMixin, DetailView):
    model = BookIssuanceAccounting
    form_class = BookIssuanceAccountingForm
    template_name = "books/accounting-book-detail.html"
    context_object_name = "book"


class BookIssuanceAccountingCreateView(LoginRequiredMixin, CreateView):
    model = BookIssuanceAccounting
    form_class = BookIssuanceAccountingForm
    template_name = "books/accounting-book-form.html"
    success_url = reverse_lazy("books:accounting_books_list")


class BookIssuanceAccountingUpdateView(LoginRequiredMixin, UpdateView):
    model = BookIssuanceAccounting
    form_class = BookIssuanceAccountingForm
    template_name = "books/accounting-book-form.html"
    success_url = reverse_lazy("books:accounting_books_list")


def debt_list(request):
    context = {"debt": (BookIssuanceAccounting.objects.filter(return_book=False))}
    return render(request,"books/debt-list.html", context)

Library/books/templates/books/author-form.html
{% extends 'base.html' %}

{% block title %}
  Create
{% endblock %}

{% block body %}
  <h1>Заполните информацию об авторе</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
  <p></p>
  <p></p>
  <div>
    <a href="{% url 'books:author_list' %}">К списку авторов</a>
  </div>
{% endblock %}

Library/books/templates/books/author-list.html
{% extends 'base.html' %}

{% block title %}
  Authors
{% endblock %}

{% block body %}
  <h1>Авторы:</h1>
  {% if authors %}
    <ul>
      {% for author in authors %}
        <li>
          <strong>
           <a href="{% url 'books:author_update' pk=author.pk %}">
             {{ author.name }}
          </a>
          </strong>
          <a {{ author.name }}></a>
          <span>
          <a href="{% url 'books:author_delete' pk=author.pk %}">
          - удалить
          </a>
          </span>
          <br>

        </li>
      <br>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Не добавлен ни один автор!</h2>
  {% endif %}
  <div>
    <a href="{% url 'books:create_author' %}">Добавить автора</a>
  </div>
<br>
  {% include "back-to-index-common.html" %}
{% endblock %}`

Library/books/templates/books/autor_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{author}}</title>
</head>
<body>
  {{author}}
</body>
</html>

Library/books/templates/books/book-detail.html
{% extends 'base.html' %}

{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{book}}</h1>
    <strong><p>жанр:  </strong>{{object.genre.name}}</p>
    <strong><p>автор: </strong>{{object.author.name}}</p>
    <strong><p>описание: </strong>{{object.description}}</p>
    <br>
    <br>
    <a href="{% url 'books:delete' pk=book.pk %}">
    удалить книгу
    </a>
    <br>
    <br>
  <div>
    <a href="{% url 'books:list' %}">К списку книг</a>
  </div>
  {% include "back-to-index-common.html" %}
{% endblock %}


Library/books/templates/books/book-form.html
{% extends 'base.html' %}

{% block title %}
  Create
{% endblock %}

{% block body %}
  <h1>Заполните информацию о книге</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
  <p></p>
  <div>
    <a href="{% url 'books:create_genre' %}">Добавить жанр</a>
    <a href="{% url 'books:create_author' %}">Добавить автора</a>
  </div>
  <p></p>
  <div>
    <a href="{% url 'books:list' %}">К списку книг</a>
  </div>
{% endblock %}

Library/books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Delete {{object.name}}
{% endblock %}

{% block body %}
  <h1>Удаление книги</h1>
    Вы хотите удалить: {{object.name}}
    <p></p>
    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit">да</button>
    </form>

  {% include "back-to-index-common.html" %}
{% endblock %}

Library/books/templates/books/copy-detail.html
{% extends 'base.html' %}

{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{"Экземпляр книги:"}} {{ object.book }}</h1>
    <p>Инвентарный номер книги: {{object.id}}</p>
    <br>
    <br>
    <a href="{% url 'books:copy_delete' pk=object.pk %}">
    удалить экземпляр
    </a>
    <br>
    <br>
  <div>
    <a href="{% url 'books:copy_list' %}"> Вернуться к инвентарным номера книг</a>
  </div>
  {% include "back-to-index-common.html" %}
{% endblock %}


Library/books/templates/books/copy-last.html
{% extends 'base.html' %}

{% block title %}
  Last copy
{% endblock %}

{% block body %}
  <h1>Инвентарный номер книги {{copy.book}} создан:</h1>
  <h2>{{copy.id}}</h2>
  <div>
    <a href="{% url 'books:copy_list' %}">Вернуться к инвентарным номерам книг</a>
  </div>
{% endblock %}

Library/books/templates/books/copy-list.html
{% extends 'base.html' %}

{% block title %}
  Books
{% endblock %}

{% block body %}
  <h1>Инвентарные номера книг:</h1>
  {% if copies_books %}
    <ul>
      {% for copy in copies_books %}
        <li>
          <strong>
            {{ copy.id }}
            <a href="{% url 'books:copy_detail' pk=copy.pk %}">{{ copy.book }}</a></strong>
          <br>
        </li>
      <br>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No books yet!</h2>
  {% endif %}
  <div>
    <a href="{% url 'books:list' %}">К списку книг</a>
    <a href="{% url 'books:create_copy' %}">Добавить экземпляр книги</a>
  </div>
<br>
  {% include "back-to-index-common.html" %}
{% endblock %}`

Library/books/templates/books/genre-form.html
{% extends 'base.html' %}

{% block title %}
  Create
{% endblock %}

{% block body %}
  <h1>Добавьте жанр</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
  <div>
    <a href="{% url 'books:genre_list' %}">К списку жанров</a>
  </div>
{% endblock %}

Library/books/templates/books/genre-list.html
{% extends 'base.html' %}

{% block title %}
  Books
{% endblock %}

{% block body %}
  <h1>Жанры книг:</h1>
  {% if genres %}
    <ul>
      {% for genre in genres %}
        <li>
          <strong>
             {{ genre.name }}
              <a href="{% url 'books:genre_delete' pk=genre.pk %}"> удалить жанр
    </a></strong>
          <br>
        </li>
      <br>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Не добавлен ни один жанр!</h2>
  {% endif %}
  <div>
    <a href="{% url 'books:create_genre' %}">Добавить жанр</a>
  </div>
<br>
  {% include "back-to-index-common.html" %}
{% endblock %}`

Library/books/templates/books/genre_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  Delete {{object.name}}
{% endblock %}

{% block body %}
  <h1>Удаление жанра {{object.genre}}</h1>
    Вы хотите удалить <strong>{{object}}</strong>
    <p></p>
    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit">да</button>
    </form>

  {% include "back-to-index-common.html" %}
{% endblock %}

Library/books/templates/books/reader-detail.html
{% extends 'base.html' %}

{% block title %}
  {{reader}}
{% endblock %}

{% block body %}
  <h1>{{reader}}</h1>
    <p>Ф.И.О.: {{reader.name}}</p>
    <p>адрес: {{reader.address}}</p>
    <p>электронная почта: {{reader.email}}</p>
    <br>
    {{ debt }}
    <br>
    <br>
    <a href="{% url 'books:reader_delete' pk=reader.pk %}">
    удалить
    </a>
    <br>
    <br>
  <div>
    <a href="{% url 'books:reader_list' %}">К списку бибилиотечных карточек</a>
  </div>
  {% include "back-to-index-common.html" %}
{% endblock %}


Library/books/templates/books/reader-list.html
{% extends 'base.html' %}

{% block title %}
  Readers
{% endblock %}

{% block body %}
  <h1>Наши читатели:</h1>
  {% if readers %}
    <ul>
      {% for reader in readers %}
        <li>
          <strong>
           <a href="{% url 'books:reader_detail' pk=reader.pk %}">
             {{ reader.name }}
           </a>
          </strong>
          <span>
          <a href="{% url 'books:reader_update' pk=reader.pk %}">
          - внести изменения
          </a>
          </span>
          <br>

        </li>
      <br>
      {% endfor %}
    </ul>
  {% else %}
    <h2>Читатели еще не добавлены!</h2>
  {% endif %}
  <div>
    <a href="{% url 'books:reader_create' %}">Добавить читателя</a>
  </div>
<br>
  {% include "back-to-index-common.html" %}
{% endblock %}`